CREATE TABLE ACCT (
    ACT_NO        INTEGER,
    CUST_NAME     VARCHAR(100),
    DOB           INTEGER,
    COUNTRY       VARCHAR(50),
    NO_OF_TX      VARCHAR(10)
);
COMMIT;

INSERT INTO ACCT (ACT_NO, CUST_NAME, DOB, COUNTRY, NO_OF_TX)
    SELECT C.ACT_NO, C.CUST_NAME, C.DOB, C.COUNTRY, CAST(COUNT(*) AS VARCHAR(10)) AS NO_OF_TX
    FROM CUST_INFO C
    LEFT JOIN TRANSACTION T
    ON C.ACT_NO = T.ACT_NO
    GROUP BY C.ACT_NO, C.CUST_NAME, C.DOB, C.COUNTRY;
COMMIT;

UPDATE ACCT SET COUNTRY = 'US' WHERE COUNTRY = 'USA';
COMMIT;

UPDATE ACCT SET NO_OF_TX = 'N/A' WHERE NO_OF_TX IS NULL;
COMMIT;

DELETE FROM ACCT WHERE DOB < DATE '1950';
COMMIT;